<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>18a369df-663f-4461-b94f-95a71e6e8166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol.breadcrumb.p-0.m-0 > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='breadcumb']/div/div/ol/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10540cb4-c0d2-40b7-8da3-7117ac57a439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/portal/</value>
      <webElementGuid>3fc51572-4978-4b17-a06e-90f0dfdd2cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>a4095f0c-ae8e-4e8a-9cee-f8dbb8d02269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcumb&quot;)/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;page-title-box&quot;]/ol[@class=&quot;breadcrumb p-0 m-0&quot;]/li[1]/a[1]</value>
      <webElementGuid>d493e636-f8fa-4759-9523-644c5784dffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='breadcumb']/div/div/ol/li/a</value>
      <webElementGuid>f305e079-afc2-4727-97c8-d0922a20fedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dashboard')]</value>
      <webElementGuid>09a3c413-c053-4350-a6ec-0fd012a519cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May25 Inc'])[2]/following::a[1]</value>
      <webElementGuid>dca9e8fd-e4ee-4f06-a519-eb679d6a3c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May25 Inc'])[1]/following::a[1]</value>
      <webElementGuid>3aa36f24-d97d-4909-b3b3-69b06d601e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Discussion'])[1]/preceding::a[1]</value>
      <webElementGuid>024a9283-5487-4572-8710-8419a4e5720f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May25 Inc'])[3]/preceding::a[1]</value>
      <webElementGuid>bd0275f7-fd5d-4416-91b1-47c76e0cfdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/portal/')])[23]</value>
      <webElementGuid>d3460dd5-8938-479c-892e-f3f645ef4b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>731028a4-32f0-49eb-b92c-1550f1005f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/portal/' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>c3f2495b-65b2-4215-b0f4-827a6c97f783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
