<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View All</name>
   <tag></tag>
   <elementGuidId>429869f9-606b-4b53-bd06-cc5fc84f86cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dash-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div/div[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2418a1e-098d-402c-ae2d-ee6b77f762b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/portal/user/conversation/list/77f6430e08ad32ace501/active</value>
      <webElementGuid>a5fb14bb-56e7-4e7d-8ae6-8ed339c253c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dash-link</value>
      <webElementGuid>b3524d57-b7a8-4bc0-ab2b-ba206bf99e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View All</value>
      <webElementGuid>921ca9af-093c-4a06-8544-fc4df921075d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-box discussions dash-discuss&quot;]/a[@class=&quot;dash-link&quot;]</value>
      <webElementGuid>b3f7416d-d20c-4c45-8eee-ff4ab14ffb21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div[3]/div/div/a</value>
      <webElementGuid>1bac82d8-f4e9-4eac-8cbc-85916aa308ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View All')]</value>
      <webElementGuid>94fcf765-4543-4e6f-8314-98e4460ed65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discussions'])[2]/following::a[1]</value>
      <webElementGuid>8860b0ad-cc6b-4b60-892e-522d4a1bb4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[3]</value>
      <webElementGuid>2ab4840d-070d-43c8-acc1-7a9825028402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May25'])[1]/preceding::a[1]</value>
      <webElementGuid>9bb21a57-a080-4e7d-8416-e1ae06ad4439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May25'])[2]/preceding::a[2]</value>
      <webElementGuid>7d8444df-e600-4287-ad2e-6f0215264b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View All']/parent::*</value>
      <webElementGuid>60fd7903-d92e-40ae-a0df-1f25ceeb77d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/portal/user/conversation/list/77f6430e08ad32ace501/active')])[2]</value>
      <webElementGuid>68cc834a-39af-41b4-9418-9f72810cee4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/a</value>
      <webElementGuid>0d42f2e4-a42c-4d93-ad9b-6bd053e6bef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/portal/user/conversation/list/77f6430e08ad32ace501/active' and (text() = 'View All' or . = 'View All')]</value>
      <webElementGuid>f7281ba0-e3e4-4a53-8966-6da9cfe6c73f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
