<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_LOGIN</name>
   <tag></tag>
   <elementGuidId>b57e06db-b398-4b17-90a9-c5689586d355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_submit > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='_submit']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>13802759-d1f5-4c68-8ea3-9d9be475db14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>060763c7-eb20-4c8d-b76b-b45a1a452235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_submit&quot;)/b[1]</value>
      <webElementGuid>369e7ce3-a4ef-462a-abd0-7216bfa7b427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='_submit']/b</value>
      <webElementGuid>a93aaff3-1eb1-4d9a-992e-2a0a7212e644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::b[1]</value>
      <webElementGuid>7134ef24-7ddb-4c93-8d41-4b3cea2d5b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/following::b[1]</value>
      <webElementGuid>22c272a3-8cb7-4708-8bdd-d4d4b8d52968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open the web profiler.'])[1]/preceding::b[1]</value>
      <webElementGuid>8deec876-bcd2-4dd6-a6a9-03ca288f94e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>1b824eb1-0fa6-417b-bc82-9612fb6b9e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/b</value>
      <webElementGuid>77679313-2aee-4f69-9969-32edd710744e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>37a84092-5c01-4907-aa3c-e9ad923f5855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
