<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Welcome,  May25</name>
   <tag></tag>
   <elementGuidId>82598fa3-32fb-4199-ab19-305774e2e678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.page-title.lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='breadcumb']/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>935a56d4-edcd-454c-9926-ef4b3a2cf25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title lg</value>
      <webElementGuid>4bc9bd0d-eb2f-4fe4-8e3b-a4f5b63e85bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome,  
May25
</value>
      <webElementGuid>a8b7d56f-02e0-4e67-ad66-74763804d435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcumb&quot;)/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;page-title-box&quot;]/h4[@class=&quot;page-title lg&quot;]</value>
      <webElementGuid>3bb9e8ea-0b9c-4bed-9322-afc8105e843b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='breadcumb']/div/div/h4</value>
      <webElementGuid>5d377dfb-8dff-434f-a29e-3fe7d2959fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::h4[1]</value>
      <webElementGuid>8e47b531-dfab-43b7-ae94-a86b8def4389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/following::h4[1]</value>
      <webElementGuid>89bb80f1-d55f-43e1-92cf-1c177314b97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::h4[1]</value>
      <webElementGuid>759844ce-7dbc-407a-b468-87dff2274a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discussions'])[2]/preceding::h4[1]</value>
      <webElementGuid>9aebc7b0-d0c7-4ef7-8855-4a29c9d863bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>c89b4b00-e09d-454d-aa25-cdc70e953ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Welcome,  
May25
' or . = 'Welcome,  
May25
')]</value>
      <webElementGuid>632c144b-e788-4ee1-b460-3381da411d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
