<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_May25</name>
   <tag></tag>
   <elementGuidId>2118a1fd-98e4-48cf-a5ce-c9fcad81f2eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.m-t-0.text-black.font-600.font16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='message-comment-d0d66007b4ec99d9ce20']/div/div[2]/div/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>627ada2d-767c-4587-9eb6-66895c836c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-t-0 text-black font-600 font16</value>
      <webElementGuid>89236bf5-eafa-40ea-a36a-6d512644e02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>May25 </value>
      <webElementGuid>6f01932d-4a57-4168-9721-85ef214752d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message-comment-d0d66007b4ec99d9ce20&quot;)/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-xs-10 col-lg-11&quot;]/div[@class=&quot;comment-content&quot;]/div[@class=&quot;comment-bubble&quot;]/h5[@class=&quot;m-t-0 text-black font-600 font16&quot;]</value>
      <webElementGuid>39498e1e-c5b6-432d-a142-f7e17a6d007e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='message-comment-d0d66007b4ec99d9ce20']/div/div[2]/div/div/h5</value>
      <webElementGuid>1a568021-77a6-4d4c-b085-8b9f9fd1c8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::h5[1]</value>
      <webElementGuid>a12a609a-1eb9-4009-8028-8b9d0a3ba2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::h5[1]</value>
      <webElementGuid>b83e4295-9d18-473a-b990-a728956a41e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update comment in discussion.'])[1]/preceding::h5[1]</value>
      <webElementGuid>2a4d019c-09c6-41ad-a747-6a507aaddde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Tracker'])[1]/preceding::h5[1]</value>
      <webElementGuid>9669e8c6-3122-4821-ba75-b7332c0ca53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='May25']/parent::*</value>
      <webElementGuid>9c873dd4-37bf-458f-b270-1dc03708a33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/h5</value>
      <webElementGuid>fb0e5a60-467b-4d86-b10b-74dbf9b8cf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'May25 ' or . = 'May25 ')]</value>
      <webElementGuid>9cda7255-c62c-4aff-b27f-5fb6884d87c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
