<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Notifications_ug-tooltip-frame</name>
   <tag></tag>
   <elementGuidId>c50a05bb-5f73-471c-b1be-de4a56ef77f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ug-tooltip-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ug-tooltip-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>230e6ada-c5fd-49aa-b908-adcdef1db7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-extension</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0923f02-c39a-46aa-a563-a1850807f8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ug-sdk__sc-1t9uwze-0 jEDHPF ug-frame-wrapper</value>
      <webElementGuid>9393e1c4-d0a5-4d43-82de-4124d66ee135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ug-tooltip-frame</value>
      <webElementGuid>589cb8d1-c767-40f7-8e79-5e1de9ac81d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ug-tooltip-frame&quot;)</value>
      <webElementGuid>ab884a50-abf6-4a4b-9065-ccb519bc9076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5da13113-f746-437f-986c-43f594b7cfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-extension</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6881215-614a-4780-9e2a-aa5ff156854e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ug-sdk__sc-1t9uwze-0 jEDHPF ug-frame-wrapper</value>
      <webElementGuid>af9016b5-8a08-4522-82cb-4fc3060d0103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ug-tooltip-frame</value>
      <webElementGuid>16c5d1eb-94bc-4bdc-8028-9c8355a3d7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ug-tooltip-frame&quot;)</value>
      <webElementGuid>009f94c8-1611-4694-a50e-d6d2d58ee8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ug-tooltip-frame']</value>
      <webElementGuid>77927968-e30f-489d-a7b1-4e363717d71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userguiding']/iframe[2]</value>
      <webElementGuid>ccafe135-0cc2-45fa-b9b1-03d1be359fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe[2]</value>
      <webElementGuid>33ffaf9a-9757-40b8-a705-1dd894189fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ug-tooltip-frame']</value>
      <webElementGuid>1f28386c-fca6-4696-969a-ef4978c844a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
