<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_LOGIN</name>
   <tag></tag>
   <elementGuidId>288788f5-df4f-456b-8cef-dcdd75bf472f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_submit > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='_submit']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>62462793-7bde-4c7a-95e2-d85698ecf3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>76c08a61-e5ab-4348-97bc-7ecdf21c7164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_submit&quot;)/b[1]</value>
      <webElementGuid>ddbd3f5e-f583-44ba-b4c2-fc46de706ae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='_submit']/b</value>
      <webElementGuid>03c76d12-c077-4bb4-8780-e749d4c26878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::b[1]</value>
      <webElementGuid>98ad748e-c420-4b36-ab6c-f100da335510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/following::b[1]</value>
      <webElementGuid>310d372c-9f45-42cc-9b4b-5c43ce7afac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open the web profiler.'])[1]/preceding::b[1]</value>
      <webElementGuid>2cc5816b-e2c0-425e-8223-1490fbe35df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>fe16fbdd-1ef6-4649-9ae2-a0b8d30aeea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/b</value>
      <webElementGuid>b9420ba4-d81a-4ae7-965c-68bddfd93a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>c90970d7-01bb-4532-bc88-1fae3f20c9b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
