<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Welcome,  May25</name>
   <tag></tag>
   <elementGuidId>2ce63e3c-02bd-4f2e-9cf4-add5cd341908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.page-title.lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='breadcumb']/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>201e8c57-8278-4156-a438-018f8bc83944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title lg</value>
      <webElementGuid>d46b1c7e-3d74-4efa-8532-f71ecf65982e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome,  
May25
</value>
      <webElementGuid>3b334791-8a0c-4f9c-8297-55e82f010f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcumb&quot;)/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;page-title-box&quot;]/h4[@class=&quot;page-title lg&quot;]</value>
      <webElementGuid>3ba9ab51-9893-4c04-a09c-4e692ba550e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='breadcumb']/div/div/h4</value>
      <webElementGuid>18cf9835-093c-4631-bb1a-02307bc43fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::h4[1]</value>
      <webElementGuid>0322b6db-fdef-4934-aba0-bda88f5d0c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/following::h4[1]</value>
      <webElementGuid>dd9b596f-49e7-4959-8167-2376e5735f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::h4[1]</value>
      <webElementGuid>fa446384-a0d5-43cb-8ba7-b32096f78bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discussions'])[2]/preceding::h4[1]</value>
      <webElementGuid>5048ae37-2f35-4d55-9cb0-dc007a228df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>82df4a29-fca6-4ece-9829-ac16c83a0a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Welcome,  
May25
' or . = 'Welcome,  
May25
')]</value>
      <webElementGuid>272c1f3c-657e-4bdb-be34-36a1aeb0631c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
