<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Notifications_ug-tooltip-frame</name>
   <tag></tag>
   <elementGuidId>4e1d29d8-f89a-4cbf-b410-5c7a3a84b6d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ug-tooltip-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ug-tooltip-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f517ce56-b54a-40f2-9a64-51e1592b9104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-extension</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15db8b52-ed97-4d73-8254-70df89a49a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ug-sdk__sc-1t9uwze-0 jEDHPF ug-frame-wrapper</value>
      <webElementGuid>01f9409b-1559-49ad-8963-3553a71856ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ug-tooltip-frame</value>
      <webElementGuid>b41cdcd8-6a88-4205-9337-51a3020cd69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ug-tooltip-frame&quot;)</value>
      <webElementGuid>6252c46d-2377-4db1-933d-26a4d601a1cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ug-tooltip-frame']</value>
      <webElementGuid>7ed64fda-b0e3-4a85-b71c-6ac296612f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userguiding']/iframe[2]</value>
      <webElementGuid>e16b87c3-9d92-4fd0-8f56-74197149a992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe[2]</value>
      <webElementGuid>582dd9f7-35d2-4a02-b5ae-535c362831b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ug-tooltip-frame']</value>
      <webElementGuid>486f7192-1bef-49e8-8e94-cd83ae989806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
