<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25</name>
   <tag></tag>
   <elementGuidId>5f1282c2-0bb5-482b-b5d1-662496accaed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.m-b-10.purple-clr > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div/div[2]/div/div/div/a/div/h3/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2746ad4f-d67b-4e72-886c-249855454b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                          25%
                                                                          </value>
      <webElementGuid>438298ee-d0c2-4f08-8543-e5c6bb74f9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row dash-four-card&quot;]/div[@class=&quot;col-lg-3 col-md-6 col-sm-6 print-col-6&quot;]/a[1]/div[@class=&quot;card-box widget-box-three&quot;]/h3[@class=&quot;m-b-10 purple-clr&quot;]/span[1]</value>
      <webElementGuid>23ff859a-71d3-4fc2-9762-6312681e7e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div[2]/div/div/div/a/div/h3/span</value>
      <webElementGuid>6bf698e7-4022-4539-813f-370551175613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[1]</value>
      <webElementGuid>ad06d39e-b64b-494f-a60a-09fe91a44d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discussions'])[2]/preceding::span[2]</value>
      <webElementGuid>b00ac93e-64bb-470c-893c-4f442d624f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::span[2]</value>
      <webElementGuid>3c88fae0-34fd-455c-9c02-ff0a7f4c6ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25%']/parent::*</value>
      <webElementGuid>5fd781e5-ac94-4e2b-9d4f-636c4090fee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span</value>
      <webElementGuid>ba669576-6dbd-469b-a288-f6aaf844960b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                                                          25%
                                                                          ' or . = '
                                                                          25%
                                                                          ')]</value>
      <webElementGuid>6461cf20-8844-4825-b3f4-7b2a17d1fe65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
